### ISSUE TITLE
Specify the max-width of individual post

### ISSUE THREAD

**Issue by bluewings** [bluewings/gatsby-starter-mdx-blog#24]
frontmatter example
```yaml
---
title: Hello World
max_width: 60rem
---
```
